### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by KoenWindey** [nalch/jetbook#2]
Hi - I'm getting an error when running the jar. See below.

```
C:\temp\jetbook-master>java -jar jetbook.jar
Starting generation
Populating temporary pdf with 1 pages.
Populating temporary pdf with qrcodesDelete temporary files
Exception in thread "main" java.util.NoSuchElementException: Key 'qrCodeSize' does not map to an existing object!
        at org.apache.commons.configuration2.AbstractConfiguration.throwMissingPropertyException(AbstractConfiguration.java:1901)
        at org.apache.commons.configuration2.AbstractConfiguration.checkNonNullValue(AbstractConfiguration.java:1888)
        at org.apache.commons.configuration2.AbstractConfiguration.getInt(AbstractConfiguration.java:1252)
        at de.nalch.jetbook.JetbookMain.main(JetbookMain.java:128)
```

Any idea how to resolve?

**Comment by nalch** [comment]
Hey Koen, could you specify the version of Java you are using (`java -version`)?

Seems like we already get a deprecation warning for unsupported reflections in version 11 at exactly this position even though it still works there.
